### ISSUE TITLE
expose CSMM_LOGLEVEL

### ISSUE THREAD

**Issue by halkeye** [ich777/docker-csmm-7dtd#5]
I would submit a PR for https://github.com/Squidly271/AppFeed/blob/54491f12560148f4237e59933909161e01bc9894/templates/ich777sRepository/ich777/CSMM-7DtD.xml but I don't know how it should work.

Ideally a dropdown with `blank`, `error`, `warn`, `info`, `debug`, `verbose`, or `silly` (i think thats the order from least to most verbose)

the app defaults to info, but for bug reporting purposes, it would be nice for someone to be able to override it.

**Comment by ich777** [comment]
Should I implement that to the cantainer? Please give me a little more insight how to start it with this options and i will change the template accordingly.

https://github.com/ich777/docker-templates/tree/master/ich777

**Comment by halkeye** [comment]
did you mean to close it?

i can't speak to the unraid bits, but `-e CSMM_LOGLEVEL=silly` does work with your image

**Comment by ich777** [comment]
Yes because I'm going to implement that in my git environment.

So this is simply an environment variable.

**Comment by ich777** [comment]
Will also update the template for the container for unraid.

**Comment by halkeye** [comment]
yep, csmm handles it, just need a way for users to change the value

**Comment by ich777** [comment]
Container, Template for Unraid and Readme are updated. Thank you!
